# Generated by Django 2.2.14 on 2020-07-30 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testfieldname_one', to=settings.AUTH_USER_MODEL)),
                ('three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testfieldname_three', to=settings.AUTH_USER_MODEL)),
                ('two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testfieldname_two', to='home.TestFieldName')),
            ],
        ),
    ]
